### ISSUE TITLE
Adding preferences (Swipe-left Menu)

### ISSUE THREAD

**Issue by limone-eth** [ParkIdle/ParkIdle-Android#15]
**- Feature name**: Preferences
**- Description**: user can set their favourite zones (home, work)
**- Requires**: adding button in the left menu
**- Due**: Beta
**- Status**: not started yet.
**- Time Estimation**: 2-3 hr

**Comment by limone-eth** [comment]
Added language (italian, english)

**Comment by Halpph** [comment]
Added Imperial/metric switch
Added Parking notification based on km radius

**Comment by Halpph** [comment]
Added Home point
